import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import Constants from "./config/constant";
import rootRouter from "./routes";
const app = express();
app.use(cors());
app.use(express.static(Constants.staticPath));
app.use(cookieParser());
app.use(express.json({ limit: Constants.jsonLimit }));
app.use(express.urlencoded({ limit: Constants.jsonLimit, extended: true }));
app.use("/api", rootRouter);
export default app;
